FROM node:carbon

WORKDIR /var/www/html

# Copy Package.json FIRST, so we can cache the install step.
COPY ./server/package.json package.json
RUN npm install

COPY ./server ./

# Expose the port, in case we're using Kubernetes
# instead of docker-compose.
EXPOSE 30001

# Run NPM start in the working directory to kick-off the node process.
CMD ["npm", "start"]
