version: '2'
services:
  # Backend server
  nodeserver:
    container_name: nodeserver
    build:
      context: .
      dockerfile: dockerfile-server
    ports:
      - 30001:30001
    volumes:
      - ./server:/var/www/html/server
      - ./config:/var/www/html/config

  # React App
  app:
    build:
      context: .
      dockerfile: dockerfile-react
    ports:
      - 30002:30002
    volumes:
      - ./app/src:/var/www/html/app/src
      - ./config:/var/www/html/config
