apiVersion: v1
kind: Service
metadata:
  name: crypto-react-svc
  labels:
    app: crypto-react
spec:
  type: NodePort
  ports:
    - port: 30002
      nodePort: 30002
      protocol: TCP
  selector:
    app: crypto-react
    tier: Frontend
    version: "1.2.1"
